version: "3.9"

services:
  # nextjs:
  #   build: .
  #   container_name: nextjs_app
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mariadb
  #   environment:
  #     DATABASE_URL: "mysql://root:password@mariadb:3306/dashboard_db"

  mariadb:
    image: mariadb:latest
    container_name: mariadb_server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dashboard_db
      MYSQL_USER: dashboard_user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
      - ADMINER_DEFAULT_DB=dashboard_db
      - ADMINER_DEFAULT_USERNAME=root
      - ADMINER_DEFAULT_PASSWORD=root
    ports:
      - "8080:8080"

#   dbgate:
#     image: dbgate/dbgate
#     container_name: dbgate_ui
#     restart: unless-stopped
#     ports:
#       - "3001:3000"
#     depends_on:
#       - mariadb
#     environment:
#       # CONNECTIONS: '[{"_id":"mariadb_conn","server":"mariadb","user":"root","password":"root","database":"dashboard_db","engine":"mysql"}]'
#       CONNECTIONS: con1

#       LABEL_con1: MariaDB
#       SERVER_con1: mariadb
#       PORT_con1: 3306
#       DATABASE_con1: dashboard_db
#       USERNAME_con1: root
#       PASSWORD_con1: root
#       ENGINE_con1: mysql

volumes:
  mariadb_data:
